#!/system/bin/sh
#
# Load MODULES
sleep 1
if [ -f /system/ppp ]
then
  echo "Not loading RMNET module as /system/ppp exists"
else
  echo "Loading RMNET module as /system/ppp doesn't exist"
  insmod /system/lib/modules/msm_rmnet.ko
fi
insmod /system/lib/modules/tun.ko
insmod /system/lib/modules/cifs.ko
insmod /system/lib/modules/nls_utf8.ko
insmod /system/lib/modules/fuse.ko
insmod /system/lib/modules/alsa-pcm-htc-leo.ko
insmod /system/lib/modules/alsa-mix-htc-leo.ko
insmod /system/lib/modules/ntfs.ko
echo "+++ TUN / CIFS  activated +++";
